#!/bin/bash
# ============================================================================
# build_fsbl.sh -- build the FSBL boot image BOOT.BIN for the ZYBO Rev B
#                  (official Xilinx toolchain only)
# ============================================================================
# Why the FSBL form: mainline U-Boot's SPL cannot program the PL bitstream at
# boot time (its FIT-FPGA path is broken), so the Xilinx way is used instead:
# BootROM loads the FSBL, the FSBL programs the PL over PCAP, then hands over
# to U-Boot.
#
# The whole flow uses only official Xilinx components, with no hand assembly:
#   1. HSI (built into xsdb) reads OUR OWN XSA and generates a reference BSP,
#      which is used only for the hardware parameters in its xparameters.h
#      (UART/SDIO clocks, SD controller CD/WP, ...).
#   2. gen_xparameters.py combines the official misc/zed template (most complete
#      set of macros), the hardware values from step 1, and the CPU clock derived
#      from ps7_init into one xparameters.h that is complete and correct.
#   3. $ES/lib/sw_apps/zynq_fsbl: official FSBL sources compiled with the
#      official copy_bsp.sh/makefile.
#   4. The flat U-Boot image is extracted from a board-validated u-boot.img (FIT)
#      by extract_uboot_from_fit.py (U-Boot proper + appended DTB) and wrapped in
#      an ELF with the official binutils -- bootgen can only read the entry
#      address from an ELF; for a raw .bin it writes ExecAddr 0 and the FSBL
#      would hand over to address 0 and hang.
#   5. bootgen combines fsbl.elf + system.bit + u-boot.elf into BOOT.BIN.
#
# Usage:
#   fsbl/build_fsbl.sh [--xsa <xsa>] [--uboot-img <u-boot.img>] [--work <dir>] [--out <dir>]
# Environment variables:
#   VIVADO (or XILINX_VIVADO), ZYBO_TOOLCHAIN, ZYBO_XSA, ZYBO_UBOOT_IMG,
#   ZYBO_FSBL_WORK, ZYBO_FSBL_OUT, ZYBO_PS7_INIT, ZYBO_CHECK_PS7
# Outputs: <out>/BOOT.BIN  <out>/fsbl.elf
# ============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"

# Vivado installation (provides xsdb, bootgen and the embeddedsw sources).
VIVADO="${VIVADO:-${XILINX_VIVADO:-}}"
[ -n "$VIVADO" ] || {
    echo "ERROR: set VIVADO (or XILINX_VIVADO) to the Vivado installation directory," >&2
    echo "       e.g. VIVADO=/opt/Xilinx/Vivado/2024.1 $0 ..." >&2
    exit 1
}
ES="${VIVADO}/data/embeddedsw"
FSBL_SRC="${ES}/lib/sw_apps/zynq_fsbl"
XSDB="${VIVADO}/bin/xsdb"
BOOTGEN="${VIVADO}/bin/bootgen"

# Optional GNU Arm bare-metal toolchain (arm-none-eabi-*). If ZYBO_TOOLCHAIN is
# set, its bin directory (and any bundled GNU Arm toolchain bin directory) is
# prepended to PATH; otherwise the tools must already be on PATH.
TC="${ZYBO_TOOLCHAIN:-}"
if [ -n "$TC" ]; then
    PATH="${TC}/bin:${PATH}"
    for d in "${TC}"/arm-gnu-toolchain-*/bin; do
        [ -d "$d" ] && PATH="$d:${PATH}"
    done
    export PATH
fi

XSA="${ZYBO_XSA:-}"
UBOOT_IMG="${ZYBO_UBOOT_IMG:-}"
UBOOT_BIN="${ZYBO_UBOOT_BIN:-}"          # empty = extract U-Boot from UBOOT_IMG (FIT)
WORK="${ZYBO_FSBL_WORK:-${HERE}/work}"
OUT="${ZYBO_FSBL_OUT:-${WORK}/out}"
# PS7 initialization data: empty = use the copy generated by apply_board_preset
# in the XSA; set to a file to use an external ps7_init.c for comparison.
PS7_INIT="${ZYBO_PS7_INIT:-}"

while [ $# -gt 0 ]; do
    case "$1" in
        --xsa)       XSA="$2"; shift 2 ;;
        --ps7-init)  PS7_INIT="$2"; shift 2 ;;
        --uboot-img) UBOOT_IMG="$2"; UBOOT_BIN=""; shift 2 ;;
        --uboot)     UBOOT_BIN="$2"; shift 2 ;;
        --work)      WORK="$2"; OUT="$2/out"; shift 2 ;;
        --out)       OUT="$2"; shift 2 ;;
        -h|--help) sed -n '2,/^set /p' "$0" | sed '$d'; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 1 ;;
    esac
done

info() { echo -e "\033[0;32m[FSBL]\033[0m $*"; }
step() { echo; echo -e "\033[0;36m-- $* -------------------------\033[0m"; }
die()  { echo -e "\033[0;31m[ERROR]\033[0m $*" >&2; exit 1; }

# -- Sanity check: official components and tools -------------------------
for f in "$XSDB" "$BOOTGEN" "${FSBL_SRC}/src/Makefile" "${FSBL_SRC}/misc/makefile" \
         "${FSBL_SRC}/misc/copy_bsp.sh" "${FSBL_SRC}/misc/zed/xparameters.h"; do
    [ -e "$f" ] || die "official component not found: $f"
done
command -v arm-none-eabi-gcc >/dev/null 2>&1 || die "arm-none-eabi-gcc not found on PATH (set ZYBO_TOOLCHAIN)"
command -v make              >/dev/null 2>&1 || die "make not found on PATH"
command -v python3           >/dev/null 2>&1 || die "python3 not found on PATH"
[ -n "$XSA" ] || die "no XSA given (use --xsa or ZYBO_XSA)"
[ -f "$XSA" ] || die "XSA not found: $XSA"
if [ -z "$UBOOT_BIN" ]; then
    [ -n "$UBOOT_IMG" ] || die "no U-Boot image given (use --uboot-img/--uboot or ZYBO_UBOOT_IMG)"
    [ -f "$UBOOT_IMG" ] || die "U-Boot source not found: $UBOOT_IMG"
fi

info "XSA        = $XSA"
info "u-boot src = ${UBOOT_BIN:-$UBOOT_IMG}"
info "work dir   = $WORK"

step "1. Extract hardware description from the XSA (hwh / ps7_init / bitstream)"
rm -rf "$WORK/xsa"; mkdir -p "$WORK/xsa"
BIT_IN_XSA="$(unzip -Z1 "$XSA" | grep -E '\.bit$' | head -1)"
HWH_IN_XSA="$(unzip -Z1 "$XSA" | grep -E '\.hwh$' | head -1)"
[ -n "$BIT_IN_XSA" ] || die "the XSA contains no .bit"
[ -n "$HWH_IN_XSA" ] || die "the XSA contains no .hwh"
unzip -o -q "$XSA" ps7_init.c ps7_init.h ps7_init_gpl.c ps7_init_gpl.h \
       "$BIT_IN_XSA" "$HWH_IN_XSA" -d "$WORK/xsa"
info "bitstream = $(basename "$BIT_IN_XSA") $(stat -c%s "$WORK/xsa/$BIT_IN_XSA") B md5 $(md5sum "$WORK/xsa/$BIT_IN_XSA" | cut -c1-12)"

if [ -n "$PS7_INIT" ]; then
    [ -f "$PS7_INIT" ] || die "file given with --ps7-init not found: $PS7_INIT"
    cp -f "$PS7_INIT" "$WORK/xsa/ps7_init.c"
    cp -f "$PS7_INIT" "$WORK/xsa/ps7_init_gpl.c"
    info "PS7 init = $PS7_INIT (md5 $(md5sum "$PS7_INIT" | cut -c1-12)) -- overrides the XSA board preset"
fi

step "2. HSI generates a reference BSP from the XSA (hardware parameters only)"
rm -rf "$WORK/bsp_hsi"
ZYBO_XSA="$XSA" ZYBO_BSP_OUT="$WORK/bsp_hsi" "$XSDB" "$HERE/gen_bsp.tcl" > "$WORK/hsi.log" 2>&1 || {
    tail -20 "$WORK/hsi.log"; die "HSI failed to generate the BSP (see $WORK/hsi.log)"; }
[ -f "$WORK/bsp_hsi/ps7_cortexa9_0/include/xparameters.h" ] || die "HSI did not generate xparameters.h"

step "3. Assemble the FSBL BSP configuration (official template + our hardware)"
mkdir -p "$WORK/misc/zybo"
cp -f "$WORK/xsa"/ps7_init*.c "$WORK/xsa"/ps7_init*.h "$WORK/misc/zybo/"
cp -f "${FSBL_SRC}/misc/zed/bspconfig.h" "${FSBL_SRC}/misc/zed/inbyte.c" \
      "${FSBL_SRC}/misc/zed/outbyte.c"   "$WORK/misc/zybo/"

# PS7 MIO configuration comes from the XSA board preset; no patching is applied
# here. An XSA built without apply_board_preset carries Vivado defaults
# (LVCMOS 3.3V / pull-up / slow) which break SD, UART and Ethernet, so the
# board design must apply the board preset when the PS7 block is created.
# At build time the board values (Ethernet MIO16..27 + MDIO52/53, SD/UART
# electrical settings, clocking) must be present in ps7_init.c. An optional
# external checker can be pointed at with ZYBO_CHECK_PS7.
# patch_ps7_mio.py is kept in this directory for diagnostics/comparison only.
CHECK_PS7="${ZYBO_CHECK_PS7:-}"
if [ -n "$CHECK_PS7" ]; then
    [ -f "$CHECK_PS7" ] || die "file given with ZYBO_CHECK_PS7 not found: $CHECK_PS7"
    python3 "$CHECK_PS7" "$WORK/misc/zybo/ps7_init.c" | sed 's/^/  /' \
        || die "ps7_init.c failed validation (PS7 may have been reset to Vivado defaults)"
fi

python3 "$HERE/gen_xparameters.py" \
    --template "${FSBL_SRC}/misc/zed/xparameters.h" \
    --hsi      "$WORK/bsp_hsi/ps7_cortexa9_0/include/xparameters.h" \
    --hwh      "$WORK/xsa/$HWH_IN_XSA" \
    --ps7init  "$WORK/xsa/ps7_init.c" \
    --out      "$WORK/misc/zybo/xparameters.h"

step "4. Copy the official FSBL sources + driver symlinks"
rm -rf "$WORK/src" "$WORK/drvlink" "$WORK/svclink"
cp -r "${FSBL_SRC}/src" "$WORK/src"
# The official copy_bsp.sh assumes it lives inside the embeddedsw source tree
# (it looks for standalone/drivers with relative paths), so it is rewritten with
# absolute paths here. Driver directories in embeddedsw carry a version suffix
# while drivers.txt lists them without one, hence the symlink layer. drivers.txt
# only lists drivers that really exist in embeddedsw and the FSBL needs.
mkdir -p "$WORK/drvlink" "$WORK/svclink"
: > "$WORK/misc/zybo/drivers.txt"
for d in devcfg emacps qspips scugic sdps ttcps uartps; do
    src="$(ls -d "${ES}/XilinxProcessorIPLib/drivers/${d}_v"* 2>/dev/null | sort -V | tail -1)"
    [ -n "$src" ] || die "driver $d not found in embeddedsw"
    ln -sfn "$src" "$WORK/drvlink/$d"
    echo "$d" >> "$WORK/misc/zybo/drivers.txt"
done
for s in xilffs xilrsa; do
    src="$(ls -d "${ES}/lib/sw_services/${s}_v"* 2>/dev/null | sort -V | tail -1)"
    [ -n "$src" ] || die "$s not found in embeddedsw"
    ln -sfn "$src" "$WORK/svclink/$s"
done
cp -f "${FSBL_SRC}/misc/config.make" "${FSBL_SRC}/misc/dep.mk" \
      "${FSBL_SRC}/misc/makefile" "${FSBL_SRC}/misc/Xilinx.spec" "$WORK/misc/"
sed -e "s|^EMBEDDED_SW_DIR=.*|EMBEDDED_SW_DIR=${ES}|" \
    -e "s|^DRIVERS_DIR=.*|DRIVERS_DIR=${WORK}/drvlink|" \
    -e "s|^SERVICES_DIR=.*|SERVICES_DIR=${WORK}/svclink|" \
    -e "s|^STANDALONE_DIR=.*|STANDALONE_DIR=${ES}/lib/bsp/standalone_v9_1/src|" \
    "${FSBL_SRC}/misc/copy_bsp.sh" > "$WORK/misc/copy_bsp.sh"
chmod +x "$WORK/misc/copy_bsp.sh"
info "drivers: $(tr '\n' ' ' < "$WORK/misc/zybo/drivers.txt")"

step "5. Build the FSBL (official makefile; it runs copy_bsp.sh internally)"
# About the macros:
#  -DFSBL_DEBUG_INFO: makes the FSBL print its progress (without it
#    fsbl_dbg_current_types stays 0 and not even "Xilinx First Stage Boot Loader"
#    is printed, leaving blind guessing when something fails).
# Do NOT define -DMMC_SUPPORT: in the official FSBL it makes the partition loop
#   start at partition 0 (image_mover.c: "In case of MMC support, boot image
#   preset in MMC will not have FSBL partition"), which is the eMMC boot-partition
#   case where BOOT.BIN does not contain the FSBL itself. Here partition 0 of the
#   SD-card BOOT.BIN IS the FSBL, so it would be treated as a PS partition with
#   LoadAddr 0, the loop would break with Handoff Address 0 and the board would
#   not boot. Without MMC_SUPPORT the loop starts at partition 1, skipping the
#   FSBL's own partition, which matches the standard layout
#   "SD-card BOOT.BIN = FSBL + bitstream + U-Boot".
#   The SD driver code (sd.c/InitSD/SDAccess) is compiled based on XPAR_XSDPS and
#   is independent of MMC_SUPPORT, so leaving it undefined still allows booting
#   from SD.
FSBL_CFLAGS="-Wall -O0 -g3 -c -fmessage-length=0 -DFSBL_DEBUG_INFO"
make -C "$WORK/src" BOARD=zybo CC=arm-none-eabi-gcc CFLAGS="$FSBL_CFLAGS" \
     > "$WORK/fsbl_build.log" 2>&1 || {
    echo "---- end of log ----"; tail -25 "$WORK/fsbl_build.log"
    die "FSBL build failed (full log: $WORK/fsbl_build.log)"; }
FSBL_ELF="$WORK/src/fsbl.elf"
[ -f "$FSBL_ELF" ] || die "no fsbl.elf produced"
info "FSBL CFLAGS = $FSBL_CFLAGS"
info "fsbl.elf = $(stat -c%s "$FSBL_ELF") B md5 $(md5sum "$FSBL_ELF" | cut -c1-12)"

step "6. Prepare flat U-Boot and wrap it in an ELF (bootgen needs an ELF entry address)"
if [ -n "$UBOOT_BIN" ]; then
    cp -f "$UBOOT_BIN" "$WORK/u-boot.bin"
    info "using the external flat image: $UBOOT_BIN"
else
    # On the SPL route u-boot.img is a FIT (external data form):
    # [FIT device tree][U-Boot proper][board dtbs...]. The FSBL route has no SPL,
    # and OF_SEPARATE U-Boot looks for the dtb at the END of the image, so
    # "U-Boot proper + this board's dtb" is assembled here.
    python3 "$HERE/extract_uboot_from_fit.py" "$UBOOT_IMG" "$WORK/u-boot.bin" zybo \
        || die "failed to extract U-Boot from $UBOOT_IMG"
fi
info "u-boot.bin = $(stat -c%s "$WORK/u-boot.bin") B md5 $(md5sum "$WORK/u-boot.bin" | cut -c1-12)"
arm-none-eabi-objcopy -I binary -O elf32-littlearm -B arm "$WORK/u-boot.bin" "$WORK/_u-boot.o"
arm-none-eabi-ld -Ttext=0x04000000 --entry=0x04000000 -o "$WORK/u-boot.elf" "$WORK/_u-boot.o"
ENTRY=$(arm-none-eabi-readelf -h "$WORK/u-boot.elf" | awk '/Entry point/{print $4}')
[ "$ENTRY" = "0x4000000" ] || die "wrong u-boot.elf entry point: $ENTRY"

step "7. bootgen combines BOOT.BIN"
cat > "$WORK/boot.bif" <<'BIFEOF'
//arch = zynq; split = false; format = BIN
the_ROM_image:
{
	[bootloader]fsbl.elf
	system.bit
	u-boot.elf
}
BIFEOF
cp -f "$WORK/xsa/$BIT_IN_XSA" "$WORK/system.bit"
cp -f "$FSBL_ELF" "$WORK/fsbl.elf"        # the BIF refers to relative file names
mkdir -p "$OUT"
( cd "$WORK" && "$BOOTGEN" -image boot.bif -arch zynq -o "$OUT/BOOT.BIN" -w on ) \
    > "$WORK/bootgen.log" 2>&1 || { tail -10 "$WORK/bootgen.log"; die "bootgen failed"; }
cp -f "$FSBL_ELF" "$OUT/fsbl.elf"

step "8. Verify BOOT.BIN (the U-Boot partition needs LoadAddr = ExecAddr = 0x04000000)"
python3 - "$OUT/BOOT.BIN" <<'PYEOF'
import struct, sys
d = open(sys.argv[1], 'rb').read()
u = lambda o: struct.unpack_from('<I', d, o)[0]
assert u(0x20) == 0xAA995566, "wrong boot header magic"
assert d[0x24:0x28] == b'XNLX', "wrong image identification"
ok = False
for o in range(0x100, 0x4000, 4):
    # partition header: [0]=ImageWordLen [4]=DataWordLen [8]=PartitionWordLen [0xc]=LoadAddr [0x10]=ExecAddr
    if u(o) == u(o+4) == u(o+8) and u(o+0xc) == 0x04000000:
        print("  partition header@0x%05x: ImageWordLen=%d LoadAddr=0x%08x ExecAddr=0x%08x"
              % (o, u(o), u(o+0xc), u(o+0x10)))
        if u(o+0x10) == 0x04000000:
            ok = True
if not ok:
    sys.exit("U-Boot partition ExecAddr is not 0x04000000 -- the FSBL would hand over to 0")
print("  OK: U-Boot partition ExecAddr is correct")
PYEOF

echo
info "done:"
ls -la "$OUT"
info "BOOT.BIN md5 = $(md5sum "$OUT/BOOT.BIN" | cut -d' ' -f1)"
