#!/usr/bin/env python3
# ============================================================================
# gen_xparameters.py — Generate the xparameters.h used by the FSBL (hardware
# parameters taken from our own hardware)
# ============================================================================
# Background: the FSBL xparameters.h is **hardware dependent**. The official
# embeddedsw only ships BSP templates for zc702/zc706/zed; borrowing zed's
# template brings in that board's parameters — it declares UART/SDIO at 50 MHz
# while ZYBO Rev B hardware runs at 100 MHz, and it declares an SD card detect
# pin (HAS_CD=1) that our PS configuration does not wire up. The FSBL SD driver
# derives its divider from InputClockHz, so a wrong value can break reading
# U-Boot.
#
# Approach (no manual edits, fully reviewable, every step traceable):
#   1. Base     = the official Xilinx misc/zed/xparameters.h (most complete set
#                 of macros, builds with the legacy makefile flow)
#   2. Override = same-named values from the xparameters.h that the HSI built
#                 into xsdb generates from **our own XSA** (UART/SDIO/ENET
#                 clocks, SD controller CD/WP, ... exported from hardware by
#                 Vivado)
#   3. Fill in  = the CPU clock, which HSI does not generate but which can be
#                 computed from hardware: ARM PLL FBDIV x PS_CLK / divider,
#                 read from the register writes in ps7_init.c and cross-checked
#                 against the ACT value in the hwh
#
# Usage:
#   gen_xparameters.py --template <zed/xparameters.h> --hsi <hsi/xparameters.h> \
#                      --hwh <x.hwh> --ps7init <ps7_init.c> --out <zybo/xparameters.h>
# ============================================================================
import argparse
import re
import sys

DEF_RE = re.compile(r'^(\s*#\s*define\s+([A-Za-z_]\w*)\s+)(\S+)(.*)$')


def parse_defs(path):
    """Return {macro name: (value, line number)}"""
    out = {}
    for i, line in enumerate(open(path, encoding='utf-8', errors='ignore'), 1):
        m = DEF_RE.match(line)
        if m:
            out[m.group(2)] = (m.group(3), i)
    return out


def norm(v):
    """Normalize for comparison: strip the U/L suffix"""
    return re.sub(r'[uUlL]+$', '', v)


def parse_ps7_clock(ps7init):
    """Compute the CPU clock from the register writes in ps7_init.c.
    ARM_PLL_CTRL(0xF8000100)[18:12] = FBDIV; ARM_CLK_CTRL(0xF8000120)[13:8] = divider;
    CPU 6x4x clock = PS_CLK(50MHz) x FBDIV / divider."""
    txt = open(ps7init, encoding='utf-8', errors='ignore').read()
    def field(addr):
        m = re.search(r'EMIT_MASKWRITE\(0X%08X,\s*(0X[0-9A-Fa-f]+)U?\s*,\s*(0X[0-9A-Fa-f]+)U?\s*\)' % addr, txt)
        if not m:
            return None
        mask, val = int(m.group(1), 16), int(m.group(2), 16)
        v = val & mask
        while mask and not (mask & 1):
            mask >>= 1
            v >>= 1
        return v
    fbdiv, div = field(0xF8000100), field(0xF8000120)
    if not fbdiv or not div:
        return None, None
    return 50_000_000 * fbdiv // div, (fbdiv, div)


def parse_hwh_act(hwh):
    m = re.search(r'PCW_ACT_APU_PERIPHERAL_FREQMHZ"\s+VALUE="([\d.]+)"', open(hwh, encoding='utf-8', errors='ignore').read())
    return int(round(float(m.group(1)) * 1_000_000)) if m else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--template', required=True, help='official BSP template (misc/zed/xparameters.h)')
    ap.add_argument('--hsi', required=True, help='xparameters.h generated by HSI from our XSA')
    ap.add_argument('--hwh', help='hwh from the XSA (source of the ACT clock)')
    ap.add_argument('--ps7init', help='ps7_init.c from the XSA (to compute the CPU clock)')
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    tmpl = open(a.template, encoding='utf-8', errors='ignore').read()
    tdefs = parse_defs(a.template)
    hdefs = parse_defs(a.hsi)

    overrides = {}   # macro name -> (new value, source)

    # (1) same-named macros taken from HSI (exported from our own hardware)
    for name, (val, _) in tdefs.items():
        if name in hdefs and norm(hdefs[name][0]) != norm(val):
            overrides[name] = (hdefs[name][0], 'HSI@XSA')

    # (2) CPU clock: HSI does not generate it, compute it from ps7_init.c and
    # cross-check against the ACT value from the hwh
    cpu_ps7, parts = (parse_ps7_clock(a.ps7init) if a.ps7init else (None, None))
    cpu_hwh = parse_hwh_act(a.hwh) if a.hwh else None
    if cpu_ps7 and cpu_hwh and abs(cpu_ps7 - cpu_hwh) > cpu_hwh * 0.01:
        print(f"  !! CPU clock differs between the two sources: ps7_init={cpu_ps7} hwh={cpu_hwh}", file=sys.stderr)
    cpu = cpu_ps7 or cpu_hwh
    if cpu:
        for name in ('XPAR_PS7_CORTEXA9_0_CPU_CLK_FREQ_HZ', 'XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ'):
            if name in tdefs:
                overrides[name] = (str(cpu), f'ps7_init FBDIV={parts[0]} divider={parts[1]}' if parts else 'hwh ACT')

    # (3) write out: replace line by line, every macro must occur exactly once
    out_lines, applied = [], set()
    for line in tmpl.splitlines(keepends=True):
        m = DEF_RE.match(line)
        if m and m.group(2) in overrides:
            name = m.group(2)
            new, _ = overrides[name]
            # replace only the value token, keep the trailing comment and newline as is
            line = re.sub(r'^(\s*#\s*define\s+%s\s+)\S+' % re.escape(name),
                          lambda mm: mm.group(1) + new, line, count=1)
            applied.add(name)
        out_lines.append(line)
    missing = sorted(set(overrides) - applied)
    if missing:
        sys.exit(f"these macros were not found in the template, cannot override: {missing}")
    open(a.out, 'w', encoding='utf-8').write(''.join(out_lines))

    print(f"  Base template: {a.template}")
    print(f"  Overriding {len(overrides)} macros (all values come from our own hardware):")
    for name in sorted(overrides):
        new, src = overrides[name]
        print(f"    {name:52s} {tdefs[name][0]:>12s} -> {new:<12s} [{src}]")

    # (4) self-check: replacement must not glue adjacent lines together
    # (a macro must be a #define at the start of a line)
    text = open(a.out, encoding='utf-8').read()
    glued = [ln for ln in text.splitlines() if re.search(r'\S\s+#\s*define', ln)]
    if glued:
        sys.exit("glued lines in the generated output:\n  " + "\n  ".join(glued[:3]))
    n_t = sum(1 for _ in (l for l in open(a.template, encoding='utf-8', errors='ignore') if DEF_RE.match(l)))
    n_o = sum(1 for _ in (l for l in text.splitlines(keepends=True) if DEF_RE.match(l)))
    if n_t != n_o:
        sys.exit(f"#define line count changed: template {n_t} -> output {n_o}")
    print(f"  Self-check: {n_o} #defines, no glued lines ✓")
    print(f"  Output: {a.out}")


if __name__ == '__main__':
    main()
